
package hethongquanlycuahangvanphongpham;

import hethongquanlycuahangvanphongpham.Model.ChiTietPN;
import hethongquanlycuahangvanphongpham.Model.SanPham;
import hethongquanlycuahangvanphongpham.Model.NhaCungCap;
import hethongquanlycuahangvanphongpham.Model.User;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSI-VN
 */
public class frm_TaoPhieuNhap extends javax.swing.JFrame {
    PreparedStatement pst = null;
    PreparedStatement pstUpdate = null;
    ResultSet rs = null;
    int rows,i;
    User user = new User();
    private ArrayList<ChiTietPN> listCTPN = new ArrayList<>();
    private ArrayList<NhaCungCap> listNCC = new ArrayList<>();
    private ArrayList<SanPham> listSP = new ArrayList<>();
    /**
     * Creates new form NhapSanPham
     */
    public frm_TaoPhieuNhap() {
        initComponents();
        this.setLocationRelativeTo(null);
        arrageMaPN();//Random mã phiếu nhập ngẫu nhiên
        JdatePN.setLocale(new Locale("vi", "VN"));//Chuyển kiểu về định dạng dd mm yyyy
        JdatePN.setDateFormatString("dd/MM/yyyy");
        try {
            loadCombobox();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Load dữ liệu thất bại");
        }
    }

   
    
    public void arrageMaPN()
    {
        int randomNumber = (int) (Math.random() * 1000001); // Tạo số ngẫu nhiên từ 0 đến 1000000
        tf_MaPN.setText("PN" + randomNumber);
        tf_MaPN.setEditable(false);// Không cho phép chỉnh sửa trực tiếp
    }

    public void loadCombobox() throws SQLException
    {
        String strNCC = "SELECT * FROM htquanlycuahangvanphongpham.nhacungcap;";
        String strSP="SELECT * FROM htquanlycuahangvanphongpham.sanpham;";
        Connection conn = ConnectionDB.getConnectDB();//Mở kết nối
        ResultSet result = ConnectionDB.getSelectResult(conn,strNCC);
        ResultSet resultSP = ConnectionDB.getSelectResult(conn,strSP);
        while(result.next())
        {
            String MaNCC = result.getString("MaNCC");
            String TenNCC = result.getString("TenNCC");
            NhaCungCap n = new NhaCungCap();
            n.setMaNCC(MaNCC);
            n.setTenNCC(TenNCC);
            listNCC.add(n);
        }
        for(int i = 0;i < listNCC.size();i++)
        {
            cb_NhaCC.addItem(listNCC.get(i).getTenNCC());
        }
        
        
          while(resultSP.next())
        {
            String MaSP = resultSP.getString("MaSanPham");
            String TenSP= resultSP.getString("TenSanPham");
            SanPham s = new SanPham();
            s.setMaSP(MaSP);
            s.setTenSP(TenSP);
            listSP.add(s);
        }
        for(int i = 0;i < listSP.size();i++)
        {
            cb_SanPham.addItem(listSP.get(i).getTenSP());
        }
        ConnectionDB.closeConnectionDB(conn);//Đóng kết nối
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cb_NhaCC = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cb_SanPham = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tf_SoLuong = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_Gia = new javax.swing.JTextField();
        btn_ThemSanPham = new javax.swing.JButton();
        btn_SuaSP = new javax.swing.JButton();
        btn_XoaSP = new javax.swing.JButton();
        btn_ResetSP = new javax.swing.JButton();
        tf_MaPN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_TaoPhieuNhap = new javax.swing.JButton();
        lb_TongTienPN = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_ChiTietPhieuNhap = new javax.swing.JTable();
        JdatePN = new com.toedter.calendar.JDateChooser();
        Lable12 = new javax.swing.JLabel();
        btn_close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Phiếu nhập Sản Phẩm");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Nhà Cung Cấp:");

        cb_NhaCC.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        cb_NhaCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_NhaCCActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sản Phẩm"));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Sản Phẩm:");

        cb_SanPham.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Số Lượng:");

        tf_SoLuong.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Giá Bán");

        tf_Gia.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        btn_ThemSanPham.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_ThemSanPham.setText("Thêm");
        btn_ThemSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemSanPhamActionPerformed(evt);
            }
        });

        btn_SuaSP.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_SuaSP.setText("Sửa");
        btn_SuaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaSPActionPerformed(evt);
            }
        });

        btn_XoaSP.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_XoaSP.setText("Xóa");
        btn_XoaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaSPActionPerformed(evt);
            }
        });

        btn_ResetSP.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_ResetSP.setText("Reset");
        btn_ResetSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResetSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_SanPham, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_SoLuong)
                            .addComponent(tf_Gia, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_ThemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_SuaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_XoaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ResetSP, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cb_SanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_Gia, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ThemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SuaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_XoaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ResetSP, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        tf_MaPN.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Mã Phiếu Nhập:");

        btn_TaoPhieuNhap.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_TaoPhieuNhap.setText("Tạo Phiếu Nhập");
        btn_TaoPhieuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaoPhieuNhapActionPerformed(evt);
            }
        });

        lb_TongTienPN.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        lb_TongTienPN.setForeground(new java.awt.Color(255, 0, 0));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel8.setText("Tổng Tiền : ");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi tiết phiếu nhập"));

        tb_ChiTietPhieuNhap.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tb_ChiTietPhieuNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sản Phẩm", "Số Lượng", "Giá"
            }
        ));
        tb_ChiTietPhieuNhap.setRowHeight(27);
        tb_ChiTietPhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_ChiTietPhieuNhapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_ChiTietPhieuNhap);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        Lable12.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        Lable12.setForeground(new java.awt.Color(255, 0, 51));
        Lable12.setText("đ");

        btn_close.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_close.setText("Thoát");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(542, 958, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(Lable12, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lb_TongTienPN, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(556, 556, 556)
                        .addComponent(btn_TaoPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tf_MaPN, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cb_NhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JdatePN, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_MaPN, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb_NhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(JdatePN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_TongTienPN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(Lable12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_TaoPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TaoPhieuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaoPhieuNhapActionPerformed
    java.util.Date selectedDate = JdatePN.getDate();
    Connection con = ConnectionDB.getConnectDB();
    String sql = "insert into htquanlycuahangvanphongpham.phieunhaphang(MaPN, MaNCC, MaNhanVien, TongTien, NgayNhap) values (?,?,?,?,?)";
       try{
        int selectedIndexNCC = cb_NhaCC.getSelectedIndex();
        String maNCC = listNCC.get(selectedIndexNCC).getMaNCC();
        // Chuyển đổi java.util.Date thành java.sql.Date
        java.sql.Date sqlDate = new java.sql.Date(selectedDate.getTime());
        pst = con.prepareStatement(sql);
        pst.setString(1, tf_MaPN.getText());
        pst.setString(2, maNCC);
        pst.setString(3, User.getMaNV());
        pst.setFloat(4, Float.parseFloat(lb_TongTienPN.getText()));
        pst.setDate(5, sqlDate);  
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Đã hoàn thành việc tạo phiếu nhập thành công");
        }
        catch(SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        ConnectionDB.closeConnectionDB(con);
        themChiTietPhieuNhap();
    

    }//GEN-LAST:event_btn_TaoPhieuNhapActionPerformed

    private void themChiTietPhieuNhap()
    {
        String sqlChiTietPN = "insert into htquanlycuahangvanphongpham.chitietphieunhap(MaPN, MaSanPham, SoLuong, Gia) values (?,?,?,?)";
        String updateSLSanPham = "UPDATE htquanlycuahangvanphongpham.sanpham SET SoLuongTon = SoLuongTon + ? " + " WHERE MaSanPham = ?";
        Connection con = ConnectionDB.getConnectDB();
        try {
            pst = con.prepareStatement(sqlChiTietPN);
            pstUpdate = con.prepareStatement(updateSLSanPham);
            DefaultTableModel model = (DefaultTableModel) tb_ChiTietPhieuNhap.getModel();
            int rowCount = model.getRowCount();
            //Duyệt từng dòng dữ liệu trong Jtable tb_ChiTietPhieuNhap
            for (int row = 0; row < rowCount; row++) {
                //Thêm chi tiết phiếu nhập
                pst.setString(1, tf_MaPN.getText());
                pst.setString(2, listCTPN.get(row).getMaSanPham());
                pst.setInt(3, listCTPN.get(row).getSoLuong());
                pst.setFloat(4, listCTPN.get(row).getGia());
                pst.executeUpdate();
                //Cập nhật số lượng trong sản phẩm
                pstUpdate.setInt(1, listCTPN.get(row).getSoLuong());
                pstUpdate.setString(2, listCTPN.get(row).getMaSanPham());
                pstUpdate.executeUpdate();
            }   
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        ConnectionDB.closeConnectionDB(con);
    }
    private void clearTextFill()
    {
        cb_SanPham.setSelectedIndex(0);
        tf_Gia.setText("");
        tf_SoLuong.setText("");
    }
    
    private void showDataTable()
    {
        DefaultTableModel modelTable = (DefaultTableModel) tb_ChiTietPhieuNhap.getModel();
        for(ChiTietPN i:listCTPN)
        {
            modelTable.addRow(new Object[]{i.getTenSanPham(),i.getSoLuong(),i.getGia()});
        }
    }
    
    private float tongTien()
    {
        float tongTien = 0;
        for(ChiTietPN i:listCTPN)
        {
            tongTien += i.getSoLuong() * i.getGia();
        }
        return tongTien;
    }
    
    private void btn_ThemSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemSanPhamActionPerformed
        try {
        ChiTietPN ct = new ChiTietPN();
        String tenSp = (String)cb_SanPham.getSelectedItem();
        int soLuong = Integer.parseInt(tf_SoLuong.getText());
        float gia = Float.parseFloat(tf_Gia.getText());
        ct.setMaSanPham(listSP.get(cb_SanPham.getSelectedIndex()).getMaSP());
        ct.setTenSanPham(tenSp);
        ct.setSoLuong(soLuong);
        ct.setGia(gia);
        ct.setMaPhieuNhap(tf_MaPN.getText());
        listCTPN.add(ct);
        lb_TongTienPN.setText(String.valueOf(tongTien()));
        DefaultTableModel modelTable = (DefaultTableModel) tb_ChiTietPhieuNhap.getModel();
        modelTable.setRowCount(0);
        showDataTable();
        clearTextFill(); 
        JOptionPane.showMessageDialog(null, "Thêm Dữ Liệu vào bảng Thành Công");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Thêm Dữ Liệu vào bảng Thất Bại");
            tf_SoLuong.requestFocus();
        }
    }//GEN-LAST:event_btn_ThemSanPhamActionPerformed

    
    private void cb_NhaCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_NhaCCActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cb_NhaCCActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
   
    }//GEN-LAST:event_formWindowClosed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
         if(JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát khỏi ứng dụng này không?", "Thoát khỏi ứng dụng", JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION)
        {
            this.dispose();
        }
       
    }//GEN-LAST:event_btn_closeActionPerformed

    private void tb_ChiTietPhieuNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_ChiTietPhieuNhapMouseClicked
        DefaultTableModel RecordTable = (DefaultTableModel)tb_ChiTietPhieuNhap.getModel();
        int selectedRow = tb_ChiTietPhieuNhap.getSelectedRow();
        String loaiSP = RecordTable.getValueAt(selectedRow, 0).toString();
        for (int i = 0; i < cb_SanPham.getItemCount(); i++) {
            if (cb_SanPham.getItemAt(i).toString().equals(loaiSP)) {
                cb_SanPham.setSelectedIndex(i);
                break;
            }
        }
        tf_SoLuong.setText(RecordTable.getValueAt(selectedRow, 1).toString());
        tf_Gia.setText(RecordTable.getValueAt(selectedRow, 2).toString());
    }//GEN-LAST:event_tb_ChiTietPhieuNhapMouseClicked

    private void btn_SuaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaSPActionPerformed
        try {
        DefaultTableModel RecordTable = (DefaultTableModel)tb_ChiTietPhieuNhap.getModel();
        int selectedRow = tb_ChiTietPhieuNhap.getSelectedRow();
        listCTPN.get(selectedRow).setSoLuong(Integer.parseInt(tf_SoLuong.getText()));
        listCTPN.get(selectedRow).setGia(Float.parseFloat(tf_Gia.getText()));
        lb_TongTienPN.setText(String.valueOf(tongTien()));
        DefaultTableModel modelTable = (DefaultTableModel) tb_ChiTietPhieuNhap.getModel();
        modelTable.setRowCount(0);
        clearTextFill();
        showDataTable(); 
        JOptionPane.showMessageDialog(null, "Sửa Dữ Liệu vào bảng Thành Công");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Sửa Dữ Liệu vào bảng Thất Bại");
            tf_SoLuong.requestFocus();
        }
    }//GEN-LAST:event_btn_SuaSPActionPerformed

    private void btn_XoaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaSPActionPerformed
        DefaultTableModel RecordTable = (DefaultTableModel)tb_ChiTietPhieuNhap.getModel();
        int selectedRow = tb_ChiTietPhieuNhap.getSelectedRow();
        listCTPN.remove(selectedRow);
        lb_TongTienPN.setText(String.valueOf(tongTien()));
        DefaultTableModel modelTable = (DefaultTableModel) tb_ChiTietPhieuNhap.getModel();
        modelTable.setRowCount(0);
        clearTextFill();
        showDataTable();
    }//GEN-LAST:event_btn_XoaSPActionPerformed

    private void btn_ResetSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResetSPActionPerformed
        cb_SanPham.setSelectedIndex(0);
        tf_Gia.setText("");
        tf_SoLuong.setText("");
    }//GEN-LAST:event_btn_ResetSPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_TaoPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_TaoPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_TaoPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_TaoPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_TaoPhieuNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JdatePN;
    private javax.swing.JLabel Lable12;
    private javax.swing.JButton btn_ResetSP;
    private javax.swing.JButton btn_SuaSP;
    private javax.swing.JButton btn_TaoPhieuNhap;
    private javax.swing.JButton btn_ThemSanPham;
    private javax.swing.JButton btn_XoaSP;
    private javax.swing.JButton btn_close;
    private javax.swing.JComboBox<String> cb_NhaCC;
    private javax.swing.JComboBox<String> cb_SanPham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_TongTienPN;
    private javax.swing.JTable tb_ChiTietPhieuNhap;
    private javax.swing.JTextField tf_Gia;
    private javax.swing.JTextField tf_MaPN;
    private javax.swing.JTextField tf_SoLuong;
    // End of variables declaration//GEN-END:variables
}
