/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hethongquanlycuahangvanphongpham;

import hethongquanlycuahangvanphongpham.Model.User;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author MSI-VN
 */
public class frm_MainJrame extends javax.swing.JFrame {

    User user = new User();
    /**
     * Creates new form MainJrame
     */
    public frm_MainJrame() {
        initComponents();

            lb_UserLogin.setText(user.getUsername());
        if(user.getQuyen().equals("User"))
        {
            ImageIcon icon = new ImageIcon("D:\\Java\\HeThongQuanLyCuaHangVanPhongPham\\src\\Images\\user.png");
            lb_image.setIcon(icon);
            menu_TaiKhoan.setVisible(false);//Ẩn menu
            menu_NhanVien.setVisible(false);//Ẩn menu
            menu_ThongKe.setVisible(false);//Ẩn menu
            menu_SanPham.setVisible(false);
            menu_NhaSanXuat.setVisible(false);
        }
        this.setLocationRelativeTo(null);//Chỉnh JFrame ra giữa màn hình
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lb_UserLogin = new javax.swing.JLabel();
        lb_image = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_SanPham = new javax.swing.JMenu();
        item_QuanLySP = new javax.swing.JMenuItem();
        menuLoai = new javax.swing.JMenuItem();
        menu_DonHang = new javax.swing.JMenu();
        item_TaoDH = new javax.swing.JMenuItem();
        item_QuanLyDH = new javax.swing.JMenuItem();
        menu_PhieuNhap = new javax.swing.JMenu();
        item_TaoPN = new javax.swing.JMenuItem();
        item_QuanLyPN = new javax.swing.JMenuItem();
        menu_NhaSanXuat = new javax.swing.JMenu();
        item_QuanLyNSX = new javax.swing.JMenuItem();
        menu_NhanVien = new javax.swing.JMenu();
        item_QuanLyNV = new javax.swing.JMenuItem();
        menu_TaiKhoan = new javax.swing.JMenu();
        item_QuanLyTK = new javax.swing.JMenuItem();
        menu_ThongKe = new javax.swing.JMenu();
        item_ThongKeDH = new javax.swing.JMenuItem();
        menu_Systems = new javax.swing.JMenu();
        item_Thoat = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem6.setText("jMenuItem6");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Hệ Thống Quản Lý Cửa Hàng Văn Phòng Phẩm");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Welcome : ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        lb_UserLogin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb_UserLogin.setForeground(new java.awt.Color(102, 102, 102));
        lb_UserLogin.setText("jLabel4");

        lb_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/programmer.png"))); // NOI18N

        jMenuBar1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        menu_SanPham.setText("Sản Phẩm");
        menu_SanPham.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        item_QuanLySP.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        item_QuanLySP.setText("Quản Lý Sản Phẩm");
        item_QuanLySP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_QuanLySPActionPerformed(evt);
            }
        });
        menu_SanPham.add(item_QuanLySP);

        menuLoai.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        menuLoai.setText("Quản Lý Loại Sản Phẩm");
        menuLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLoaiActionPerformed(evt);
            }
        });
        menu_SanPham.add(menuLoai);

        jMenuBar1.add(menu_SanPham);

        menu_DonHang.setText("Đơn Hàng");
        menu_DonHang.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        item_TaoDH.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        item_TaoDH.setText("Tạo Đơn Hàng");
        item_TaoDH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_TaoDHActionPerformed(evt);
            }
        });
        menu_DonHang.add(item_TaoDH);

        item_QuanLyDH.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        item_QuanLyDH.setText("Quản Lý Đơn Hàng");
        item_QuanLyDH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_QuanLyDHActionPerformed(evt);
            }
        });
        menu_DonHang.add(item_QuanLyDH);

        jMenuBar1.add(menu_DonHang);

        menu_PhieuNhap.setText("Phiếu Nhập");
        menu_PhieuNhap.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        item_TaoPN.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        item_TaoPN.setText("Tạo Phiếu Nhập");
        item_TaoPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_TaoPNActionPerformed(evt);
            }
        });
        menu_PhieuNhap.add(item_TaoPN);

        item_QuanLyPN.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        item_QuanLyPN.setText("Quản Lý Phiếu Nhập");
        item_QuanLyPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_QuanLyPNActionPerformed(evt);
            }
        });
        menu_PhieuNhap.add(item_QuanLyPN);

        jMenuBar1.add(menu_PhieuNhap);

        menu_NhaSanXuat.setText("Nhà Sản Xuất");
        menu_NhaSanXuat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        item_QuanLyNSX.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        item_QuanLyNSX.setText("Quản Lí Nhà Sản Xuất");
        item_QuanLyNSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_QuanLyNSXActionPerformed(evt);
            }
        });
        menu_NhaSanXuat.add(item_QuanLyNSX);

        jMenuBar1.add(menu_NhaSanXuat);

        menu_NhanVien.setText("Nhân Viên");
        menu_NhanVien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        item_QuanLyNV.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        item_QuanLyNV.setText("Quản Lý Nhân Viên");
        item_QuanLyNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_QuanLyNVActionPerformed(evt);
            }
        });
        menu_NhanVien.add(item_QuanLyNV);

        jMenuBar1.add(menu_NhanVien);

        menu_TaiKhoan.setText("Tài Khoản");
        menu_TaiKhoan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        item_QuanLyTK.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        item_QuanLyTK.setText("Quản Lý Tài Khoản");
        item_QuanLyTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_QuanLyTKActionPerformed(evt);
            }
        });
        menu_TaiKhoan.add(item_QuanLyTK);

        jMenuBar1.add(menu_TaiKhoan);

        menu_ThongKe.setText("Thống Kê");
        menu_ThongKe.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        item_ThongKeDH.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        item_ThongKeDH.setText("Thống Kê Đơn Hàng");
        item_ThongKeDH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_ThongKeDHActionPerformed(evt);
            }
        });
        menu_ThongKe.add(item_ThongKeDH);

        jMenuBar1.add(menu_ThongKe);

        menu_Systems.setText("Hệ Thống");
        menu_Systems.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        item_Thoat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        item_Thoat.setText("Thoát");
        item_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_ThoatActionPerformed(evt);
            }
        });
        menu_Systems.add(item_Thoat);

        jMenuBar1.add(menu_Systems);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_UserLogin)
                        .addGap(150, 150, 150)
                        .addComponent(lb_image)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(81, 81, 81))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_image)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lb_UserLogin)
                            .addComponent(jLabel3))))
                .addGap(165, 165, 165)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void item_TaoPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_TaoPNActionPerformed
        frm_TaoPhieuNhap frm = new frm_TaoPhieuNhap();
        frm.setVisible(true);
    }//GEN-LAST:event_item_TaoPNActionPerformed

    private void item_QuanLyNSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_QuanLyNSXActionPerformed
        frm_NhaCungCap frm = new frm_NhaCungCap();
        frm.setVisible(true);
    }//GEN-LAST:event_item_QuanLyNSXActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        frm_MainJrame frm = new frm_MainJrame();
        frm.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void item_QuanLyPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_QuanLyPNActionPerformed
        frm_QuanLyPhieuNhap frm = new frm_QuanLyPhieuNhap();
        frm.setVisible(true);
    }//GEN-LAST:event_item_QuanLyPNActionPerformed

    private void item_QuanLyNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_QuanLyNVActionPerformed
        try {
            frmNhanVien frm = new frmNhanVien();
            frm.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(frm_MainJrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_item_QuanLyNVActionPerformed

    private void item_TaoDHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_TaoDHActionPerformed
       frm_TaoHoaDon frm = new frm_TaoHoaDon();
       frm.setVisible(true);
    }//GEN-LAST:event_item_TaoDHActionPerformed

    private void item_QuanLyDHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_QuanLyDHActionPerformed
        frm_QuanLyHoaDon frm = new frm_QuanLyHoaDon();
        frm.setVisible(true);
    }//GEN-LAST:event_item_QuanLyDHActionPerformed

    private void item_QuanLyTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_QuanLyTKActionPerformed
        try {
            frmTaiKhoan frm = new frmTaiKhoan();
            frm.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(frm_MainJrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_item_QuanLyTKActionPerformed

    private void item_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_ThoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_item_ThoatActionPerformed

    private void item_QuanLySPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_QuanLySPActionPerformed
        frmQuanLySanPham frm;
        try {
            frm = new frmQuanLySanPham();
            frm.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(frm_MainJrame.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_item_QuanLySPActionPerformed

    private void item_ThongKeDHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_ThongKeDHActionPerformed
       ThongKe frm = new ThongKe();
       frm.setVisible(true);
    }//GEN-LAST:event_item_ThongKeDHActionPerformed

    private void menuLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoaiActionPerformed
        frm_LoaiSanPham frm;
        try {
            frm = new frm_LoaiSanPham();
            frm.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(frm_MainJrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuLoaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_MainJrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_MainJrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_MainJrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_MainJrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_MainJrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem item_QuanLyDH;
    private javax.swing.JMenuItem item_QuanLyNSX;
    private javax.swing.JMenuItem item_QuanLyNV;
    private javax.swing.JMenuItem item_QuanLyPN;
    private javax.swing.JMenuItem item_QuanLySP;
    private javax.swing.JMenuItem item_QuanLyTK;
    private javax.swing.JMenuItem item_TaoDH;
    private javax.swing.JMenuItem item_TaoPN;
    private javax.swing.JMenuItem item_Thoat;
    private javax.swing.JMenuItem item_ThongKeDH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JLabel lb_UserLogin;
    private javax.swing.JLabel lb_image;
    private javax.swing.JMenuItem menuLoai;
    private javax.swing.JMenu menu_DonHang;
    private javax.swing.JMenu menu_NhaSanXuat;
    private javax.swing.JMenu menu_NhanVien;
    private javax.swing.JMenu menu_PhieuNhap;
    private javax.swing.JMenu menu_SanPham;
    private javax.swing.JMenu menu_Systems;
    private javax.swing.JMenu menu_TaiKhoan;
    private javax.swing.JMenu menu_ThongKe;
    // End of variables declaration//GEN-END:variables
}
