/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hethongquanlycuahangvanphongpham;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSI-VN
 */
public class frm_QuanLyPhieuNhap extends javax.swing.JFrame {
        PreparedStatement pst = null;
        ResultSet resultSet = null;
        int columns;
    /**
     * Creates new form QuanLyPhieuNhap
     */
    public frm_QuanLyPhieuNhap() {
        initComponents();
        this.setLocationRelativeTo(null);
        JdateQLPN.setLocale(new Locale("vi", "VN"));//Chuyển kiểu về định dạng dd mm yyyy
        JdateQLPN.setDateFormatString("dd/MM/yyyy");
            try {
                LoadData();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_PhieuNhap = new javax.swing.JTable();
        btn_TimKiemMaPN = new javax.swing.JButton();
        tf_MaPN = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_ChiTietPhieuNhap = new javax.swing.JTable();
        btn_closeQLHD = new javax.swing.JButton();
        btn_TaoMoiPhieuNhap = new javax.swing.JButton();
        JdateQLPN = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Quản Lý Phiếu Nhâp");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh Sách Phiếu Nhập"));

        tb_PhieuNhap.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tb_PhieuNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MaPN", "Nhà Cung Cấp", "Tổng Tiền", "Ngày Nhập", "Nhân Viên"
            }
        ));
        tb_PhieuNhap.setRowHeight(27);
        tb_PhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_PhieuNhapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_PhieuNhap);

        btn_TimKiemMaPN.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_TimKiemMaPN.setText("Tìm Kiếm");
        btn_TimKiemMaPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemMaPNActionPerformed(evt);
            }
        });

        tf_MaPN.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tf_MaPN, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_TimKiemMaPN)
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_MaPN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TimKiemMaPN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi Tiết Phiếu Nhập"));

        tb_ChiTietPhieuNhap.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tb_ChiTietPhieuNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Phiếu Nhập", "Sản Phẩm", "Số Lượng", "Giá"
            }
        ));
        tb_ChiTietPhieuNhap.setRowHeight(27);
        jScrollPane2.setViewportView(tb_ChiTietPhieuNhap);

        btn_closeQLHD.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_closeQLHD.setText("Thoát");
        btn_closeQLHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeQLHDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_closeQLHD, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_closeQLHD, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btn_TaoMoiPhieuNhap.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_TaoMoiPhieuNhap.setText("Tạo mới phiếu nhập");
        btn_TaoMoiPhieuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaoMoiPhieuNhapActionPerformed(evt);
            }
        });

        JdateQLPN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JdateQLPNMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JdateQLPNMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                JdateQLPNMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(423, 423, 423))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JdateQLPN, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(btn_TaoMoiPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1047, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addComponent(JdateQLPN, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(102, 102, 102)
                    .addComponent(btn_TaoMoiPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(452, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void LoadData() throws SQLException
        {
            Connection con = ConnectionDB.getConnectDB();
            String sql = "SELECT pn.MaPN, pn.MaNCC, ncc.TenNCC, pn.MaNhanVien, nv.TenNhanVien, pn.TongTien, pn.NgayNhap " +
             "FROM htquanlycuahangvanphongpham.phieunhaphang pn " +
             "INNER JOIN htquanlycuahangvanphongpham.nhacungcap ncc ON pn.MaNCC = ncc.MaNCC " +
             "INNER JOIN htquanlycuahangvanphongpham.nhanvien nv ON pn.MaNhanVien = nv.MaNhanVien";
            try
            {
            pst = con.prepareStatement(sql);
            resultSet = pst.executeQuery();
            
            ResultSetMetaData stData = resultSet.getMetaData();
            columns = stData.getColumnCount();
            DefaultTableModel Table = (DefaultTableModel)tb_PhieuNhap.getModel();
            Table.setRowCount(0);
            while(resultSet.next()){
                Vector columnData = new Vector();
                for(int i=1; i<=columns; i++)
                {
                    columnData.add(resultSet.getString("MaPN"));
                    columnData.add(resultSet.getString("TenNCC"));
                    columnData.add(resultSet.getString("TongTien"));
                    columnData.add(resultSet.getString("NgayNhap"));  
                    columnData.add(resultSet.getString("TenNhanVien"));
                }
                Table.addRow(columnData);
                }
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex);
            }
            ConnectionDB.closeConnectionDB(con);
        }
    private void btn_TimKiemMaPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemMaPNActionPerformed
        Connection con = ConnectionDB.getConnectDB();
            String sql = "SELECT pn.MaPN, pn.MaNCC, ncc.TenNCC, pn.MaNhanVien, nv.TenNhanVien, pn.TongTien, pn.NgayNhap " +
             "FROM htquanlycuahangvanphongpham.phieunhaphang pn " +
             "INNER JOIN htquanlycuahangvanphongpham.nhacungcap ncc ON pn.MaNCC = ncc.MaNCC " +
             "INNER JOIN htquanlycuahangvanphongpham.nhanvien nv ON pn.MaNhanVien = nv.MaNhanVien where pn.MaPN = ?";
            try
            {
            pst = con.prepareStatement(sql);
            pst.setString(1, tf_MaPN.getText());
            resultSet = pst.executeQuery();
            ResultSetMetaData stData = resultSet.getMetaData();
            columns = stData.getColumnCount();
            DefaultTableModel Table = (DefaultTableModel)tb_PhieuNhap.getModel();
            Table.setRowCount(0);
            while(resultSet.next()){
                Vector columnData = new Vector();
                for(int i=1; i<=columns; i++)
                {
                    columnData.add(resultSet.getString("MaPN"));
                    columnData.add(resultSet.getString("TenNCC"));
                    columnData.add(resultSet.getString("TongTien"));
                    columnData.add(resultSet.getString("NgayNhap"));  
                    columnData.add(resultSet.getString("TenNhanVien"));
                }
                Table.addRow(columnData);
                }
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex);
            }
            ConnectionDB.closeConnectionDB(con);
    }//GEN-LAST:event_btn_TimKiemMaPNActionPerformed

    private void tb_PhieuNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_PhieuNhapMouseClicked
        DefaultTableModel TablePN = (DefaultTableModel)tb_PhieuNhap.getModel();
        int SelectedRows = tb_PhieuNhap.getSelectedRow();
        Connection con = ConnectionDB.getConnectDB();
            String sql = "SELECT ctpn.MaPN, ctpn.MaSanPham, sp.TenSanPham, ctpn.SoLuong, ctpn.Gia " +
             "FROM htquanlycuahangvanphongpham.chitietphieunhap ctpn " +
             "INNER JOIN htquanlycuahangvanphongpham.phieunhaphang pn ON ctpn.MaPN = pn.MaPN " +
             "INNER JOIN htquanlycuahangvanphongpham.sanpham sp ON ctpn.MaSanPham = sp.MaSanPham " +
             "WHERE ctpn.MaPN = ?";
            try
            {
            pst = con.prepareStatement(sql);
            pst.setString(1, TablePN.getValueAt(SelectedRows, 0).toString());
            resultSet = pst.executeQuery();
            
            ResultSetMetaData stData = resultSet.getMetaData();
            columns = stData.getColumnCount();
            DefaultTableModel TableCTPN = (DefaultTableModel)tb_ChiTietPhieuNhap.getModel();
            TableCTPN.setRowCount(0);
            while(resultSet.next()){
                Vector columnData = new Vector();
                for(int i=1; i<=columns; i++)
                {
                    columnData.add(resultSet.getString("MaPN"));
                    columnData.add(resultSet.getString("TenSanPham"));
                    columnData.add(resultSet.getString("SoLuong"));
                    columnData.add(resultSet.getString("Gia")); 
                }
                TableCTPN.addRow(columnData);
                }
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex);
            }
        ConnectionDB.closeConnectionDB(con);    
   
    }//GEN-LAST:event_tb_PhieuNhapMouseClicked

    private void JdateQLPNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JdateQLPNMouseClicked
         Connection con = ConnectionDB.getConnectDB();
            String sql = "SELECT pn.MaPN, pn.MaNCC, ncc.TenNCC, pn.MaNhanVien, nv.TenNhanVien, pn.TongTien, pn.NgayNhap " +
                        "FROM htquanlycuahangvanphongpham.phieunhaphang pn " +
                        "INNER JOIN htquanlycuahangvanphongpham.nhacungcap ncc ON pn.MaNCC = ncc.MaNCC " +
                        "INNER JOIN htquanlycuahangvanphongpham.nhanvien nv ON pn.MaNhanVien = nv.MaNhanVien where pn.NgayNhap = ?";
            java.util.Date selectedDate = JdateQLPN.getDate();
            java.sql.Date sqlDate = new java.sql.Date(selectedDate.getTime());
            try
            {
            pst = con.prepareStatement(sql);
            pst.setDate(1, sqlDate);
            resultSet = pst.executeQuery();
            
            ResultSetMetaData stData = resultSet.getMetaData();
            columns = stData.getColumnCount();
            DefaultTableModel Table = (DefaultTableModel)tb_PhieuNhap.getModel();
            Table.setRowCount(0);
            while(resultSet.next()){
                Vector columnData = new Vector();
                for(int i=1; i<=columns; i++)
                {
                    columnData.add(resultSet.getString("MaPN"));
                    columnData.add(resultSet.getString("TenNCC"));
                    columnData.add(resultSet.getString("TongTien"));
                    columnData.add(resultSet.getString("NgayNhap"));  
                    columnData.add(resultSet.getString("TenNhanVien"));
                }
                Table.addRow(columnData);
                }
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex);
            }
            ConnectionDB.closeConnectionDB(con);
    }//GEN-LAST:event_JdateQLPNMouseClicked

    private void JdateQLPNMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JdateQLPNMouseReleased
         Connection con = ConnectionDB.getConnectDB();
            String sql = "SELECT pn.MaPN, pn.MaNCC, ncc.TenNCC, pn.MaNhanVien, nv.TenNhanVien, pn.TongTien, pn.NgayNhap " +
                        "FROM htquanlycuahangvanphongpham.phieunhaphang pn " +
                        "INNER JOIN htquanlycuahangvanphongpham.nhacungcap ncc ON pn.MaNCC = ncc.MaNCC " +
                        "INNER JOIN htquanlycuahangvanphongpham.nhanvien nv ON pn.MaNhanVien = nv.MaNhanVien where pn.NgayNhap = ?";
            java.util.Date selectedDate = JdateQLPN.getDate();
            java.sql.Date sqlDate = new java.sql.Date(selectedDate.getTime());
            try
            {
            pst = con.prepareStatement(sql);
            pst.setDate(1, sqlDate);
            resultSet = pst.executeQuery();
            
            ResultSetMetaData stData = resultSet.getMetaData();
            columns = stData.getColumnCount();
            DefaultTableModel Table = (DefaultTableModel)tb_PhieuNhap.getModel();
            Table.setRowCount(0);
            while(resultSet.next()){
                Vector columnData = new Vector();
                for(int i=1; i<=columns; i++)
                {
                    columnData.add(resultSet.getString("MaPN"));
                    columnData.add(resultSet.getString("TenNCC"));
                    columnData.add(resultSet.getString("TongTien"));
                    columnData.add(resultSet.getString("NgayNhap"));  
                    columnData.add(resultSet.getString("TenNhanVien"));
                }
                Table.addRow(columnData);
                }
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex);
            }
            ConnectionDB.closeConnectionDB(con);
    }//GEN-LAST:event_JdateQLPNMouseReleased

    private void JdateQLPNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JdateQLPNMousePressed
        Connection con = ConnectionDB.getConnectDB();
            String sql = "SELECT pn.MaPN, pn.MaNCC, ncc.TenNCC, pn.MaNhanVien, nv.TenNhanVien, pn.TongTien, pn.NgayNhap " +
                        "FROM htquanlycuahangvanphongpham.phieunhaphang pn " +
                        "INNER JOIN htquanlycuahangvanphongpham.nhacungcap ncc ON pn.MaNCC = ncc.MaNCC " +
                        "INNER JOIN htquanlycuahangvanphongpham.nhanvien nv ON pn.MaNhanVien = nv.MaNhanVien where pn.NgayNhap = ?";
            java.util.Date selectedDate = JdateQLPN.getDate();
            java.sql.Date sqlDate = new java.sql.Date(selectedDate.getTime());
            try
            {
            pst = con.prepareStatement(sql);
            pst.setDate(1, sqlDate);
            resultSet = pst.executeQuery();
            
            ResultSetMetaData stData = resultSet.getMetaData();
            columns = stData.getColumnCount();
            DefaultTableModel Table = (DefaultTableModel)tb_PhieuNhap.getModel();
            Table.setRowCount(0);
            while(resultSet.next()){
                Vector columnData = new Vector();
                for(int i=1; i<=columns; i++)
                {
                    columnData.add(resultSet.getString("MaPN"));
                    columnData.add(resultSet.getString("TenNCC"));
                    columnData.add(resultSet.getString("TongTien"));
                    columnData.add(resultSet.getString("NgayNhap"));  
                    columnData.add(resultSet.getString("TenNhanVien"));
                }
                Table.addRow(columnData);
                }
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex);
            }
            ConnectionDB.closeConnectionDB(con);
    }//GEN-LAST:event_JdateQLPNMousePressed

    private void btn_TaoMoiPhieuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaoMoiPhieuNhapActionPerformed
        frm_TaoPhieuNhap frm = new frm_TaoPhieuNhap();
        frm.setVisible(true);
    }//GEN-LAST:event_btn_TaoMoiPhieuNhapActionPerformed

    private void btn_closeQLHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeQLHDActionPerformed
         if(JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát khỏi ứng dụng này không?", "Thoát khỏi ứng dụng", JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION)
        {
            this.dispose();
        }
    }//GEN-LAST:event_btn_closeQLHDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_QuanLyPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_QuanLyPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_QuanLyPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_QuanLyPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_QuanLyPhieuNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JdateQLPN;
    private javax.swing.JButton btn_TaoMoiPhieuNhap;
    private javax.swing.JButton btn_TimKiemMaPN;
    private javax.swing.JButton btn_closeQLHD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb_ChiTietPhieuNhap;
    private javax.swing.JTable tb_PhieuNhap;
    private javax.swing.JTextField tf_MaPN;
    // End of variables declaration//GEN-END:variables
}
