/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hethongquanlycuahangvanphongpham;

import hethongquanlycuahangvanphongpham.Model.ChiTietHoaDon;
import hethongquanlycuahangvanphongpham.Model.ChiTietPN;
import hethongquanlycuahangvanphongpham.Model.NhaCungCap;
import hethongquanlycuahangvanphongpham.Model.SanPham;
import hethongquanlycuahangvanphongpham.Model.User;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSI-VN
 */
public class frm_TaoHoaDon extends javax.swing.JFrame {
    PreparedStatement pst = null;
    PreparedStatement pstUpdate = null;
    ResultSet rs = null;
    int rows,i;
    User user = new User();
    private float tongTien = 0;
    private ArrayList<ChiTietHoaDon> listCTHD = new ArrayList<>();
    private ArrayList<SanPham> listSP = new ArrayList<>();
    /**
     * Creates new form NhapHoaDon
     */
    public frm_TaoHoaDon() {
        initComponents();
        arrageMaHD();//Random mã hóa đơn ngẫu nhiên
        this.setLocationRelativeTo(null);
        JdateHD.setLocale(new Locale("vi", "VN"));//Chuyển kiểu về định dạng dd mm yyyy
        JdateHD.setDateFormatString("dd/MM/yyyy");
        try {
            loadCombobox();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Load dữ liệu thất bại");
        }
    }
    
    
     public void arrageMaHD()
    {
        int randomNumber = (int) (Math.random() * 1000001); // Tạo số ngẫu nhiên từ 0 đến 1000000
        tf_MaHD.setText("HD" + randomNumber);
        tf_MaHD.setEditable(false);// Không cho phép chỉnh sửa trực tiếp
    }
     
     public void loadCombobox() throws SQLException
    {
        String strSP="SELECT * FROM htquanlycuahangvanphongpham.sanpham;";
        Connection conn = ConnectionDB.getConnectDB();
        ResultSet resultSP = ConnectionDB.getSelectResult(conn,strSP);
          while(resultSP.next())
        {
            String MaSP = resultSP.getString("MaSanPham");
            String TenSP= resultSP.getString("TenSanPham");
            float Gia= resultSP.getFloat("Gia");
            SanPham s = new SanPham();
            s.setMaSP(MaSP);
            s.setTenSP(TenSP);
            s.setGia(Gia);
            listSP.add(s);
        }
        for(int i = 0;i < listSP.size();i++)
        {
            cb_SanPham.addItem(listSP.get(i).getTenSP());
        }
        ConnectionDB.closeConnectionDB(conn);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_MaHD = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cb_SanPham = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tf_SoLuong = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_Gia = new javax.swing.JTextField();
        btn_ThemSanPham = new javax.swing.JButton();
        btn_SuaSP = new javax.swing.JButton();
        btn_XoaSP = new javax.swing.JButton();
        btn_ResetSP = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_ChiTietHoaDon = new javax.swing.JTable();
        btn_TaoHoaDon = new javax.swing.JButton();
        JdateHD = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        lable12 = new javax.swing.JLabel();
        lb_TongTienHD = new javax.swing.JLabel();
        btn_closeHD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Tạo Hóa Đơn");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Mã Hóa Đơn :");

        tf_MaHD.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        tf_MaHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_MaHDActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sản Phẩm"));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Sản Phẩm:");

        cb_SanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_SanPhamMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Số Lượng:");

        tf_SoLuong.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Giá Bán");

        tf_Gia.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        btn_ThemSanPham.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_ThemSanPham.setText("Thêm");
        btn_ThemSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemSanPhamActionPerformed(evt);
            }
        });

        btn_SuaSP.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_SuaSP.setText("Sửa");
        btn_SuaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaSPActionPerformed(evt);
            }
        });

        btn_XoaSP.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_XoaSP.setText("Xóa");
        btn_XoaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaSPActionPerformed(evt);
            }
        });

        btn_ResetSP.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_ResetSP.setText("Reset");
        btn_ResetSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResetSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_ThemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_SuaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_XoaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ResetSP, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_SanPham, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_SoLuong)
                            .addComponent(tf_Gia, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cb_SanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_Gia, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ThemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SuaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_XoaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ResetSP, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi tiết phiếu nhập"));

        tb_ChiTietHoaDon.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tb_ChiTietHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sản Phẩm", "Số Lượng", "Giá"
            }
        ));
        tb_ChiTietHoaDon.setRowHeight(27);
        tb_ChiTietHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_ChiTietHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_ChiTietHoaDon);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btn_TaoHoaDon.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_TaoHoaDon.setText("Tạo Hóa Đơn");
        btn_TaoHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaoHoaDonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        jLabel8.setText("Tổng Tiền : ");

        lable12.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        lable12.setForeground(new java.awt.Color(255, 0, 51));
        lable12.setText("đ");

        lb_TongTienHD.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        lb_TongTienHD.setForeground(new java.awt.Color(255, 0, 0));

        btn_closeHD.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_closeHD.setText("Thoát");
        btn_closeHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeHDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_MaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JdateHD, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_closeHD, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_TaoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(568, 568, 568))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(518, 518, 518))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(lable12, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_TongTienHD, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(tf_MaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JdateHD, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(lable12)
                    .addComponent(lb_TongTienHD, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_TaoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_closeHD, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void clearTextFill()
    {
        tf_Gia.setText("");
        tf_SoLuong.setText("");
    }
    private void showDataTable()
    {
        DefaultTableModel modelTable = (DefaultTableModel) tb_ChiTietHoaDon.getModel();
        for(ChiTietHoaDon i:listCTHD)
        {
            modelTable.addRow(new Object[]{i.getTenSP(),i.getSoLuong(),i.getGia()});
        }
    }
    private void btn_ThemSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemSanPhamActionPerformed
    try {
            ChiTietHoaDon ct = new ChiTietHoaDon();
            String tenSp = (String)cb_SanPham.getSelectedItem();
            int soLuong = Integer.parseInt(tf_SoLuong.getText());
            float gia = Float.parseFloat(tf_Gia.getText());
            ct.setMaSP(listSP.get(cb_SanPham.getSelectedIndex()).getMaSP());
            ct.setTenSP(tenSp);
            ct.setSoLuong(soLuong);
            ct.setGia(gia);
            ct.setMaHD(tf_MaHD.getText());
            tongTien += (soLuong*gia);
            lb_TongTienHD.setText(String.valueOf(tongTien));
            listCTHD.add(ct);
            DefaultTableModel modelTable = (DefaultTableModel) tb_ChiTietHoaDon.getModel();
            modelTable.setRowCount(0);
            showDataTable();
            clearTextFill();
            JOptionPane.showMessageDialog(null, "Thêm Dữ Liệu vào bảng Thành Công");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Không có dữ liệu thất bại", "Error", JOptionPane.ERROR_MESSAGE);
            tf_SoLuong.requestFocus();//Focus vào 
        }
          
    }//GEN-LAST:event_btn_ThemSanPhamActionPerformed

    private void btn_TaoHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaoHoaDonActionPerformed
    java.util.Date selectedDate = JdateHD.getDate();
    Connection con = ConnectionDB.getConnectDB();
    String sql = "insert into htquanlycuahangvanphongpham.hoadon(MaHD, ThanhTien,MaNhanVien, ) values (?,?,?,?)";
       try{
       java.sql.Date sqlDate = new java.sql.Date(selectedDate.getTime());
        pst = con.prepareStatement(sql);
        pst.setString(1, tf_MaHD.getText());
        pst.setFloat(2, Float.parseFloat(lb_TongTienHD.getText()));
        pst.setDate(3, sqlDate);
        pst.setString(4, User.getMaNV());
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Đã hoàn thành việc tạo phiếu nhập thành công");
        }
        catch(SQLException ex) {
            JOptionPane.showMessageDialog(null, "Tạo hóa đơn thất bại", "Error", JOptionPane.ERROR_MESSAGE);
        }
        ConnectionDB.closeConnectionDB(con);
        themChiTietHoaDon();
    }//GEN-LAST:event_btn_TaoHoaDonActionPerformed

    private void themChiTietHoaDon()
    {
        String sqlChiTietPN = "insert into htquanlycuahangvanphongpham.chitiethoadon(MaHD, MaSanPham, SoLuong, Gia) values (?,?,?,?)";
        String updateSLSanPham = "UPDATE htquanlycuahangvanphongpham.sanpham SET SoLuongTon = SoLuongTon - ? " + " WHERE MaSanPham = ?";
        Connection con = ConnectionDB.getConnectDB();
        try {
            pst = con.prepareStatement(sqlChiTietPN);
            pstUpdate = con.prepareStatement(updateSLSanPham);
            DefaultTableModel model = (DefaultTableModel) tb_ChiTietHoaDon.getModel();
            int rowCount = model.getRowCount();
            for (int row = 0; row < rowCount; row++) {
                //Thêm chi tiết phiếu nhập
                pst.setString(1, tf_MaHD.getText());
                pst.setString(2, listCTHD.get(row).getMaSP());
                pst.setInt(3, listCTHD.get(row).getSoLuong());
                pst.setFloat(4, listCTHD.get(row).getGia());
                pst.executeUpdate();
                //Cập nhật số lượng trong sản phẩm
                pstUpdate.setInt(1, listCTHD.get(row).getSoLuong());
                pstUpdate.setString(2, listCTHD.get(row).getMaSP());
                pstUpdate.executeUpdate();
            }   
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Thêm chi tiết hóa đơn thất bại lỗi :" + ex, "Error", JOptionPane.ERROR_MESSAGE);
        }
        ConnectionDB.closeConnectionDB(con);
    }
    private float tongTien()
    {
        float tongTien = 0;
        for(ChiTietHoaDon i:listCTHD)
        {
            tongTien += i.getSoLuong() * i.getGia();
        }
        return tongTien;
    }
    private void tf_MaHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_MaHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_MaHDActionPerformed

    private void cb_SanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_SanPhamMouseClicked
        int itemSelect = cb_SanPham.getSelectedIndex();
        tf_Gia.setText(String.valueOf(listSP.get(itemSelect).getGia()));
    }//GEN-LAST:event_cb_SanPhamMouseClicked

    private void btn_closeHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeHDActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát khỏi ứng dụng này không?", "Thoát khỏi ứng dụng", JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION)
        {
            this.dispose();
        }
    }//GEN-LAST:event_btn_closeHDActionPerformed

    private void btn_SuaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaSPActionPerformed
        try {
            DefaultTableModel RecordTable = (DefaultTableModel)tb_ChiTietHoaDon.getModel();
            int selectedRow = tb_ChiTietHoaDon.getSelectedRow();
            listCTHD.get(selectedRow).setSoLuong(Integer.parseInt(tf_SoLuong.getText()));
            listCTHD.get(selectedRow).setGia(Float.parseFloat(tf_Gia.getText()));
            lb_TongTienHD.setText(String.valueOf(tongTien()));
            DefaultTableModel modelTable = (DefaultTableModel) tb_ChiTietHoaDon.getModel();
            modelTable.setRowCount(0);
            clearTextFill();
            showDataTable();
            JOptionPane.showMessageDialog(null, "Sửa Dữ Liệu vào bảng Thành Công");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Sửa Dữ Liệu vào bảng Thất Bại");
            tf_SoLuong.requestFocus();
        }
    }//GEN-LAST:event_btn_SuaSPActionPerformed

    private void btn_XoaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaSPActionPerformed
        try {
            DefaultTableModel RecordTable = (DefaultTableModel)tb_ChiTietHoaDon.getModel();
            int selectedRow = tb_ChiTietHoaDon.getSelectedRow();
            listCTHD.remove(selectedRow);
            DefaultTableModel modelTable = (DefaultTableModel) tb_ChiTietHoaDon.getModel();
            modelTable.setRowCount(0);
            clearTextFill();
            showDataTable();
            JOptionPane.showMessageDialog(null, "Xóa Dữ Liệu vào bảng Thành Công");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Không có dữ liệu trong bảng !!!", "Error", JOptionPane.ERROR_MESSAGE);

            tf_SoLuong.requestFocus();
        }
    }//GEN-LAST:event_btn_XoaSPActionPerformed

    private void btn_ResetSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResetSPActionPerformed
        cb_SanPham.setSelectedIndex(0);
        tf_Gia.setText("");
        tf_SoLuong.setText("");
    }//GEN-LAST:event_btn_ResetSPActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
    }//GEN-LAST:event_formMouseClicked

    private void tb_ChiTietHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_ChiTietHoaDonMouseClicked
        DefaultTableModel RecordTable = (DefaultTableModel)tb_ChiTietHoaDon.getModel();
        int selectedRow = tb_ChiTietHoaDon.getSelectedRow();
        String loaiSP = RecordTable.getValueAt(selectedRow, 0).toString();
        for (int i = 0; i < cb_SanPham.getItemCount(); i++) {
            if (cb_SanPham.getItemAt(i).toString().equals(loaiSP)) {
                cb_SanPham.setSelectedIndex(i);
                break;
            }
        }
        tf_SoLuong.setText(RecordTable.getValueAt(selectedRow, 1).toString());
        tf_Gia.setText(RecordTable.getValueAt(selectedRow, 2).toString());
    }//GEN-LAST:event_tb_ChiTietHoaDonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_TaoHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_TaoHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_TaoHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_TaoHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_TaoHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JdateHD;
    private javax.swing.JButton btn_ResetSP;
    private javax.swing.JButton btn_SuaSP;
    private javax.swing.JButton btn_TaoHoaDon;
    private javax.swing.JButton btn_ThemSanPham;
    private javax.swing.JButton btn_XoaSP;
    private javax.swing.JButton btn_closeHD;
    private javax.swing.JComboBox<String> cb_SanPham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lable12;
    private javax.swing.JLabel lb_TongTienHD;
    private javax.swing.JTable tb_ChiTietHoaDon;
    private javax.swing.JTextField tf_Gia;
    private javax.swing.JTextField tf_MaHD;
    private javax.swing.JTextField tf_SoLuong;
    // End of variables declaration//GEN-END:variables
}
