/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hethongquanlycuahangvanphongpham;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSI-VN
 */
public class frm_QuanLyHoaDon extends javax.swing.JFrame {
        PreparedStatement pst = null;
        ResultSet resultSet = null;
        int columns;
    /**
     * Creates new form QuanLyHoaDon
     */
    public frm_QuanLyHoaDon() {
        initComponents();
        this.setLocationRelativeTo(null);
            try {
                LoadData();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_TaoMoiHoaDon = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_HoaDon = new javax.swing.JTable();
        btn_TimKiemMaHD = new javax.swing.JButton();
        tf_MaHD = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_ChiTietHoaDon = new javax.swing.JTable();
        btn_closeQLHD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Quản Lý Hóa Đơn");

        btn_TaoMoiHoaDon.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_TaoMoiHoaDon.setText("Tạo mới hóa đơn");
        btn_TaoMoiHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaoMoiHoaDonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh Sách Hóa Đơn"));

        tb_HoaDon.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tb_HoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Hóa Đơn", "Thành Tiền", "Ngày Mua", "Nhân Viên"
            }
        ));
        tb_HoaDon.setRowHeight(27);
        tb_HoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_HoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_HoaDon);

        btn_TimKiemMaHD.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_TimKiemMaHD.setText("Tìm Kiếm");
        btn_TimKiemMaHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemMaHDActionPerformed(evt);
            }
        });

        tf_MaHD.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tf_MaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_TimKiemMaHD)
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_MaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TimKiemMaHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi Tiết Hóa Đơn"));

        tb_ChiTietHoaDon.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tb_ChiTietHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Hóa Đơn", "Sản Phẩm", "Số Lượng", "Giá"
            }
        ));
        tb_ChiTietHoaDon.setRowHeight(27);
        jScrollPane2.setViewportView(tb_ChiTietHoaDon);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_closeQLHD.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_closeQLHD.setText("Thoát");
        btn_closeQLHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeQLHDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_TaoMoiHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_closeQLHD, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(441, 441, 441))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_TaoMoiHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_closeQLHD, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void LoadData() throws SQLException
        {
            Connection con = ConnectionDB.getConnectDB();
            String sql = "SELECT hd.MaHD, hd.ThanhTien, hd.NgayMua, nv.TenNhanVien " +
             "FROM htquanlycuahangvanphongpham.hoadon hd " +
             "INNER JOIN htquanlycuahangvanphongpham.nhanvien nv ON hd.MaNhanVien = nv.MaNhanVien";
            try
            {
            pst = con.prepareStatement(sql);
            resultSet = pst.executeQuery();
            
            ResultSetMetaData stData = resultSet.getMetaData();
            columns = stData.getColumnCount();
            DefaultTableModel Table = (DefaultTableModel)tb_HoaDon.getModel();
            Table.setRowCount(0);
            while(resultSet.next()){
                Vector columnData = new Vector();
                for(int i=1; i<=columns; i++)
                {
                    columnData.add(resultSet.getString("MaHD"));
                    columnData.add(resultSet.getString("ThanhTien"));
                    columnData.add(resultSet.getString("NgayMua")); 
                    columnData.add(resultSet.getString("TenNhanVien"));
                }
                Table.addRow(columnData);
                }
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex);
            }
            ConnectionDB.closeConnectionDB(con);
        }
    private void btn_TimKiemMaHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemMaHDActionPerformed
        String sql = "";
        Connection con = ConnectionDB.getConnectDB();
        if(tf_MaHD.getText().equals(""))
         {
                sql = "SELECT hd.MaHD, hd.ThanhTien, hd.NgayMua, nv.TenNhanVien " +
                "FROM htquanlycuahangvanphongpham.hoadon hd " +
                "INNER JOIN htquanlycuahangvanphongpham.nhanvien nv ON hd.MaNhanVien = nv.MaNhanVien where 1 = 1";
         }
         else
         {
            sql = "SELECT hd.MaHD, hd.ThanhTien, hd.NgayMua, nv.TenNhanVien " +
            "FROM htquanlycuahangvanphongpham.hoadon hd " +
            "INNER JOIN htquanlycuahangvanphongpham.nhanvien nv ON hd.MaNhanVien = nv.MaNhanVien where hd.MaHD = ?";
            
            try
            {
            pst = con.prepareStatement(sql);
            pst.setString(1, tf_MaHD.getText());
            resultSet = pst.executeQuery();
            
            ResultSetMetaData stData = resultSet.getMetaData();
            columns = stData.getColumnCount();
            DefaultTableModel Table = (DefaultTableModel)tb_HoaDon.getModel();
            Table.setRowCount(0);
            while(resultSet.next()){
                Vector columnData = new Vector();
                for(int i=1; i<=columns; i++)
                {
                    columnData.add(resultSet.getString("MaHD"));
                    columnData.add(resultSet.getString("ThanhTien"));
                    columnData.add(resultSet.getString("NgayMua")); 
                    columnData.add(resultSet.getString("TenNhanVien"));
                }
                Table.addRow(columnData);
                }
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex);
            }
            ConnectionDB.closeConnectionDB(con);
         }
            
    }//GEN-LAST:event_btn_TimKiemMaHDActionPerformed

    private void btn_TaoMoiHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaoMoiHoaDonActionPerformed
        frm_TaoPhieuNhap frm = new frm_TaoPhieuNhap();
        frm.setVisible(true);
    }//GEN-LAST:event_btn_TaoMoiHoaDonActionPerformed

    private void tb_HoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_HoaDonMouseClicked
        DefaultTableModel TablePN = (DefaultTableModel)tb_HoaDon.getModel();
        int SelectedRows = tb_HoaDon.getSelectedRow();
        Connection con = ConnectionDB.getConnectDB();
            String sql = "SELECT cthd.MaHD, sp.TenSanPham, cthd.SoLuong, cthd.Gia " +
             "FROM htquanlycuahangvanphongpham.chitiethoadon cthd " +
             "INNER JOIN htquanlycuahangvanphongpham.hoadon hd ON cthd.MaHD = hd.MaHD " +
             "INNER JOIN htquanlycuahangvanphongpham.sanpham sp ON cthd.MaSanPham = sp.MaSanPham " +
             "WHERE cthd.MaHD = ?";
            try
            {
            pst = con.prepareStatement(sql);
            pst.setString(1, TablePN.getValueAt(SelectedRows, 0).toString());
            resultSet = pst.executeQuery();
            
            ResultSetMetaData stData = resultSet.getMetaData();
            columns = stData.getColumnCount();
            DefaultTableModel TableCTPN = (DefaultTableModel)tb_ChiTietHoaDon.getModel();
            TableCTPN.setRowCount(0);
            while(resultSet.next()){
                Vector columnData = new Vector();
                for(int i=1; i<=columns; i++)
                {
                    columnData.add(resultSet.getString("MaHD"));
                    columnData.add(resultSet.getString("TenSanPham"));
                    columnData.add(resultSet.getString("SoLuong"));
                    columnData.add(resultSet.getString("Gia")); 
                }
                TableCTPN.addRow(columnData);
                }
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex);
            }
        ConnectionDB.closeConnectionDB(con);
    }//GEN-LAST:event_tb_HoaDonMouseClicked

    private void btn_closeQLHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeQLHDActionPerformed
         if(JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát khỏi ứng dụng này không?", "Thoát khỏi ứng dụng", JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION)
        {
            this.dispose();
        }
    }//GEN-LAST:event_btn_closeQLHDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_QuanLyHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_QuanLyHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_QuanLyHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_QuanLyHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_QuanLyHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_TaoMoiHoaDon;
    private javax.swing.JButton btn_TimKiemMaHD;
    private javax.swing.JButton btn_closeQLHD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb_ChiTietHoaDon;
    private javax.swing.JTable tb_HoaDon;
    private javax.swing.JTextField tf_MaHD;
    // End of variables declaration//GEN-END:variables
}
